DROP TABLE IF EXISTS brand;
DROP TABLE IF EXISTS product;

CREATE TABLE product (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  article TEXT UNIQUE NOT NULL,
  title TEXT,
  brand_id INTEGER,
  FOREIGN KEY (brand_id) REFERENCES brand (id)
);

CREATE TABLE brand (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);